[package]
name = "api"
version = "0.1.0"
authors = ["Joe Chasinga <jo.chasinga@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
actix-web = "1.0.3"
futures = "0.1.28"

